# -*- coding: utf-8 -*-
"""custom_layer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181dwAeJ_2GpDFjfpCRcCwlYaPG6vlBTY
"""

import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras.saving import register_keras_serializable

@register_keras_serializable()
def custom_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)

    # penalti jika prediksi mendekati 0.5 (tidak confident)
    penalty = tf.reduce_mean(tf.abs(y_pred - 0.5))

    return bce + (0.1 * (1 - penalty))

@register_keras_serializable()
class FeatureScalingLayer(Layer):
    def __init__(self, units=64, **kwargs):
        super().__init__(**kwargs)
        self.units = units  # Inisialisasi atribut

    def build(self, input_shape):
        # Inisialisasi weight
        self.w = self.add_weight(
            name="kernel",
            shape=(input_shape[-1], self.units),
            initializer="glorot_uniform",
            trainable=True
        )

        # Inisialisasi bias
        self.b = self.add_weight(
            name="bias",
            shape=(self.units,),
            initializer="zeros",
            trainable=True
        )

        # Weight tambahan untuk scaling fitur
        self.scale = self.add_weight(
            name="scale",
            shape=(self.units,),
            initializer="ones",
            trainable=True
        )

    def call(self, inputs):
        # Proses perhitungan utama
        x = tf.matmul(inputs, self.w) + self.b

        # Scaling fitur (elemen-wise)
        x = x * self.scale

        # Aktivasi
        return tf.nn.relu(x)