# -*- coding: utf-8 -*-
"""Inference_Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R5LmOXloCbrMIZrB3SwhRFoOOb2AKkyH
"""

# ===============================================
# HAPUS KLO UDH DI LOKAL :D
# ===============================================
from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from custom_layer import FeatureScalingLayer
from custom_layer import custom_loss

# ===============================================
# NANTI DIGANTI UNTUK LOKAL :D
# ===============================================
model = tf.keras.models.load_model(
    "/content/model2.keras",
    custom_objects={'custom_loss': custom_loss, 'FeatureScalingLayer': FeatureScalingLayer}
)

import cv2
import numpy as np
from PIL import Image

IMG_SIZE = (224, 224)

# =========================
# 1. LOAD IMAGE
# =========================
def load_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    return image


# =========================
# 2. PREPROCESS FOR CNN
# =========================
def preprocess_for_cnn(image):
    img = Image.fromarray(image)
    img = img.resize(IMG_SIZE)

    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    return img_array


# ============================================================
# 3. PREPROCESS FOR OCR (Bisa diubah sesuai kebutuhan OCR :D)
# ============================================================
def preprocess_for_ocr(image):
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

    # denoise
    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    # threshold (biar teks lebih jelas)
    thresh = cv2.adaptiveThreshold(
        blur,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11,
        2
    )

    return thresh


# =========================
# 4. CNN CLASSIFIER
# =========================
def predict_receipt(image_array):
    pred = model.predict(image_array, verbose=0)[0][0]

    label = "struk" if pred > 0.5 else "non_struk"
    confidence = float(pred if pred > 0.5 else 1 - pred)

    return label, confidence

# =========================
# ROI (REGION OF INTEREST) //klo make nnt hehe//
# ROI = bagian penting dari sebuah gambar yang ingin kita fokuskan
# ROI = bagian struk yang berisi teks penting (item, harga, total)
# Manfaat ROI: OCR lebih cepat, OCR lebih akurat, noise berkurang, fokus hanya ke teks penting
# Sistem : Image --> ROI --> OCR --> Output teks
# Jika ROI berhasil, maka OCR hanya mendapatkan area penting saja
# Jika ROI gagal, maka OCR mendapatkan image utuh (fallback)
# =========================

# =========================
# 5. OCR ENGINE (PLACEHOLDER)
# =========================
def run_ocr(ocr_image):
    """
    Akan diimplementasikan oleh tim OCR:
    - Tesseract
    - EasyOCR
    """
    raise NotImplementedError("OCR belum diintegrasikan oleh tim OCR")


# =========================
# 6. PARSER HASIL OCR
# =========================
def parse_receipt(text):
    """
    Akan dikembangkan menjadi:
    - item list
    - harga
    - total
    """
    return {
        "raw_text": text
    }


# =========================
# 7. FULL PIPELINE
# =========================
def inference_pipeline(image_path):

    # 1. load image
    image = load_image(image_path)

    # 2. preprocessing (split CNN & OCR)
    cnn_input = preprocess_for_cnn(image)
    ocr_input = preprocess_for_ocr(image)

    # 3. CNN prediction
    label, confidence = predict_receipt(cnn_input)

    # 4. filter non-struk
    if label == "non_struk":
        return {
            "status": "rejected",
            "stage": "cnn",
            "reason": "Bukan struk",
            "confidence": confidence
        }

    # 5. OCR (placeholder)
    text = run_ocr(ocr_input)

    # 6. parsing
    data = parse_receipt(text)

    # 7. output final
    return {
        "status": "success",
        "stage": "cnn+ocr+parser",
        "cnn_confidence": confidence,
        "data": data
    }